CREATE TABLE
  rooms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(256) NOT NULL
  );

CREATE TABLE
  users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(256),
    nickname VARCHAR(50),
    country_code VARCHAR(2),
    phone_number VARCHAR(20),
    profile_picture VARCHAR(256)
  );